### ISSUE TITLE
After flashing minimal the plug doesn't work

### ISSUE THREAD

**Issue by StomaNL** [DzurisHome/ESPHome-Refoss-P11#1]
**Describe the bug**
After flashing the tasmota-minimal firmware the device becomes unresponsive, LED is red and the buttons doesn't do anything, socket power is on. Also no wifi connection or visible AP. Tried to reset by holding button for 40 sec but no succes

**Reproduce**
Just flash tasmota-minimal and this happens, tried on 2 and both same result.

**Comment by milandzuris** [comment]
> **Describe the bug** After flashing the tasmota-minimal firmware the device becomes unresponsive, LED is red and the buttons doesn't do anything, socket power is on. Also no wifi connection or visible AP. Tried to reset by holding button for 40 sec but no succes
> 
> **Reproduce** Just flash tasmota-minimal and this happens, tried on 2 and both same result.

Hi, hmm interesting, maybe you try first install tasmota minimal and after try install bottom cfg, and after installation try add [entire cfg](https://github.com/DzurisHome/ESPHome-Refoss-P11/blob/main/ESPHome%20Config/Refoss%20P11.yaml)

esphome:
  name: refoss-p11-dzuris-home
esp8266:
  board: esp01_1m
logger:
  baud_rate: 0
wifi:
  ssid: #SSID or !secret wifi_ssid
  password: #Password or !secret wifi_password
  manual_ip: #If you don't want set manual IPs, Delete (manual_ip and below that)
    static_ip: #Refoss P11 Device IP
    gateway: #Router IP
    subnet: #Router Subnet IP
  ap:
    ssid: "Refoss P11 Dzuriš Home AP"
    password: #Acess Point password or !secret ap_password
captive_portal:
ota:
  safe_mode: true
  password: #Password or !secret ota_password

**Comment by milandzuris** [comment]
> **Describe the bug** After flashing the tasmota-minimal firmware the device becomes unresponsive, LED is red and the buttons doesn't do anything, socket power is on. Also no wifi connection or visible AP. Tried to reset by holding button for 40 sec but no succes
> 
> **Reproduce** Just flash tasmota-minimal and this happens, tried on 2 and both same result.

Hi, this is normal Socket stop unresponsive, but here is problem why u don't have AP, i can't really help you with this, try the tasmota community, I did it this way and everything worked.

**Comment by StomaNL** [comment]
I got it working with the 3rd plug I have, you need to flash tasmota-minimal version 12.4, the same version the plug ships with.

Maybe it also works when first upgrade to the latest version, reconfig the template because it forgets it and then flash that version tasmota-minimal image. I don't know if there is a benefit to this, if so it's worth the try.

**Comment by lucaspr** [comment]
Only to find this thread with 1 working plug, 2 bricked plugs and 1 broken plug. I flashed tas minimal 14.4.1 onto the plugs. Then the full esphome binary. That did not go as expected, although it says update succesfull.. no way back now.

Only my led is green and i can hear the relais 'clicking'  for about 40 seconds. No luck in hard resetting

Blackadder should add a link to this site! Thanx for the info!
